# -*- coding: utf-8 -*-
"""kripto-2enkripsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFDpLfAKd-czZcelifyxrfnwq-dV_ieI
"""

# pip install pycipher

from pycipher import Vigenere
from pycipher import Beaufort
plain_text=input("Enter the message: ")
key=input("Enter the key: ")
vigenere_cipher = Vigenere (key).encipher(plain_text)
beaufort_cipher = Beaufort (key).encipher(vigenere_cipher)
d = Beaufort (key).decipher(beaufort_cipher)
e = Vigenere (key).decipher(d)

print("---BEAUFORT CIPHER---")
print("CIPHER TEXT : ",beaufort_cipher)
print("PLAIN TEXT : ",e)

# print("---VIGENERE CIPHER---")
# print("CIPHER TEXT : ",vigenere_cipher)
